# Generated by Django 6.1.1 on 2026-10-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='día de la semana (default)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha específica (override)')),
                ('max_appointments', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para usar únicamente la capacidad calculada del personal. 0 es válido.', null=True, verbose_name='cupo máximo de citas')),
                ('is_open', models.BooleanField(default=True, verbose_name='abierto para citas')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='nota / descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'configuración de día',
                'verbose_name_plural': 'configuraciones de días',
                'ordering': ['date', 'weekday'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('weekday__isnull', False)), fields=('weekday',), name='unique_day_config_weekday'), models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('date',), name='unique_day_config_date'), models.CheckConstraint(condition=models.Q(models.Q(('weekday__isnull', False), ('date__isnull', True)), models.Q(('weekday__isnull', True), ('date__isnull', False)), _connector='OR'), name='day_config_either_weekday_or_date')],
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'solicitante',
                'verbose_name_plural': 'solicitantes',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('phone', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='requester_phone_or_email_required')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duración en minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 60)), name='service_duration_range')],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('kind', models.CharField(choices=[('ABSENCE', 'Ausencia'), ('SPECIAL_HOURS', 'Horario especial')], max_length=20, verbose_name='tipo de excepción')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de entrada')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de salida')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='inicio de descanso')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='fin de descanso')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='agenda.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'excepción de horario',
                'verbose_name_plural': 'excepciones de horario',
                'ordering': ['worker', 'date'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='unique_worker_date_exception'), models.CheckConstraint(condition=models.Q(models.Q(('break_end__isnull', True), ('break_start__isnull', True), ('end_time__isnull', True), ('kind', 'ABSENCE'), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('kind', 'SPECIAL_HOURS'), ('start_time__isnull', False), ('start_time__lt', models.F('end_time')), models.Q(models.Q(('break_start__isnull', True), ('break_end__isnull', True)), models.Q(('break_start__isnull', False), ('break_end__isnull', False), ('break_start__gte', models.F('start_time')), ('break_start__lt', models.F('break_end')), ('break_end__lte', models.F('end_time'))), _connector='OR')), _connector='OR'), name='schedule_exception_valid_structure')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de entrada')),
                ('end_time', models.TimeField(verbose_name='hora de salida')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='inicio de descanso')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='fin de descanso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agenda.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'horario laboral',
                'verbose_name_plural': 'horarios laborales',
                'ordering': ['worker', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'weekday'), name='unique_worker_weekday_schedule'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='work_schedule_start_lt_end'), models.CheckConstraint(condition=models.Q(models.Q(('break_start__isnull', True), ('break_end__isnull', True)), models.Q(('break_start__isnull', False), ('break_end__isnull', False)), _connector='OR'), name='work_schedule_break_all_or_nothing'), models.CheckConstraint(condition=models.Q(('break_start__isnull', True), models.Q(('break_start__gte', models.F('start_time')), ('break_start__lt', models.F('break_end')), ('break_end__lte', models.F('end_time'))), _connector='OR'), name='work_schedule_break_within_shift')],
            },
        ),
    ]
