# Generated by Django 6.1.1 on 2026-10-07 22:17

import agenda.models.appointment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(

            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='fecha')),
                ('start_at', models.DateTimeField(verbose_name='inicio')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('CONFIRMED', 'Confirmada'), ('WAITLISTED', 'En espera'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No presentado'), ('RESCHEDULED', 'Reprogramada'), ('EXPIRED', 'Expirada')], max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='agenda.requester', verbose_name='solicitante')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='agenda.appointment', verbose_name='reprogramada desde')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='agenda.service', verbose_name='servicio')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='agenda.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='estado anterior')),
                ('to_status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('CONFIRMED', 'Confirmada'), ('WAITLISTED', 'En espera'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No presentado'), ('RESCHEDULED', 'Reprogramada'), ('EXPIRED', 'Expirada')], max_length=20, verbose_name='estado nuevo')),
                ('note', models.TextField(blank=True, default='', verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agenda.appointment', verbose_name='cita')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agenda.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'evento de cita',
                'verbose_name_plural': 'eventos de cita',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'status'], name='appointment_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['worker', 'date'], name='appointment_worker_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='appointment_end_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('worker__isnull', False), _connector='OR'), name='appointment_confirmed_has_worker'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'WAITLISTED'), _negated=True), ('worker__isnull', True), _connector='OR'), name='appointment_waitlisted_no_worker'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=agenda.models.appointment.PostgresExclusionConstraint(condition=models.Q(('status__in', frozenset(['COMPLETED', 'CONFIRMED', 'NO_SHOW']))), expressions=[('worker', '='), (agenda.models.appointment.TsTzRange('start_at', 'end_at'), '&&')], name='appointment_exclude_overlapping_worker'),
        ),
    ]
