# Generated by Django 6.1.1 on 2026-10-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_appointment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='número de reprogramaciones'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_children', to='agenda.appointment', verbose_name='reprogramada desde'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('rescheduled_from__isnull', True), models.Q(('rescheduled_from', models.F('id')), _negated=True), _connector='OR'), name='appointment_rescheduled_from_not_self'),
        ),
    ]
