# Generated by Django 6.1.1 on 2026-10-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_appointment_reschedule_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='manage_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='hash de token de gestión'),
        ),
    ]
