# Generated by Django 6.1.1 on 2026-10-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_appointment_manage_token_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requester',
            name='requester_phone_or_email_required',
        ),
        migrations.AddField(
            model_name='requester',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='anonimizado el'),
        ),
        migrations.AddConstraint(
            model_name='requester',
            constraint=models.CheckConstraint(condition=models.Q(('anonymized_at__isnull', False), models.Q(('phone', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='requester_phone_or_email_required'),
        ),
    ]
