# Generated by Django 6.1.1 on 2026-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_requester_requester_phone_or_email_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayconfig',
            name='booking_max_advance_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días máximos a futuro para reservar. Vacío para heredar del sistema.', null=True, verbose_name='ventana máxima a futuro (días)'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='booking_min_advance_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de anticipación mínima. Vacío para heredar del sistema.', null=True, verbose_name='anticipación mínima para agendar (horas)'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='cancel_min_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de anticipación mínima para cancelar. Vacío para heredar del sistema.', null=True, verbose_name='anticipación mínima para cancelar (horas)'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='default_slot_step_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Paso de cuadrícula en minutos (ej. 15). Vacío para heredar del sistema.', null=True, verbose_name='granularidad de horarios (minutos)'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='max_active_per_requester_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Citas activas por solicitante en esta fecha. Vacío para heredar del sistema.', null=True, verbose_name='máximo de citas activas por solicitante/día'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='max_reschedules_per_appointment',
            field=models.PositiveIntegerField(blank=True, help_text='Reprogramaciones permitidas por cita. Vacío para heredar del sistema.', null=True, verbose_name='máximo de reprogramaciones por cita'),
        ),
        migrations.AddField(
            model_name='dayconfig',
            name='waitlist_max_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad máxima de la lista de espera. Vacío para heredar del sistema.', null=True, verbose_name='tope de lista de espera por día'),
        ),
    ]
